// AUTH
export const SET_INSTITUTION = "SET_INSTITUTION"
export const LOGOUT = "LOGOUT"

// ERRORS
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR"
export const SET_NEW_TEACHER_ERROR = "SET_NEW_TEACHER_ERROR"
export const SET_EDITTING_TEACHER_ERROR = "SET_EDITTING_TEACHER_ERROR"

// SUBJECTS
export const SET_SUBJECTS = "SET_SUBJECTS"

// TEACHERS
export const REFRESH_LIST = "REFRESH_LIST"
export const GET_EDITING_TEACHER = "GET_EDITING_TEACHER"
export const SET_EDITTING_TEACHER = "SET_EDITTING_TEACHER"
export const SET_PRESENTED_TEACHER = "SET_PRESENTED_TEACHER"

// ALERT
export const OPEN_ALERT = "OPEN_ALERT"
export const CLOSE_ALERT = "CLOSE_ALERT"