// AUTH
export const SET_INSTITUTION = "SET_INSTITUTION"
export const LOGOUT = "LOGOUT"

// ERRORS
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR"
export const REMOVE_LOGIN_ERROR = "REMOVE_LOGIN_ERROR"

// SUBJECTS
export const SET_SUBJECTS = "SET_SUBJECTS"

// TEACHERS
export const REFRESH_LIST = "REFRESH_LIST"